In [ ]:
!pip install scipy

Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (1.11.4)
Requirement already satisfied: numpy<1.28.0,>=1.21.6 in /usr/local/lib/python3.10/dist-packages (from scipy) (1.25.2)

In [ ]:
!pip install statsmodels

Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (0.14.1)
Requirement already satisfied: numpy<2,>=1.18 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.25.2)
Requirement already satisfied: scipy!=1.9.2,>=1.4 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.11.4)
Requirement already satisfied: pandas!=2.1.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.5.3)
Requirement already satisfied: patsy>=0.5.4 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (0.5.6)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (23.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas!=2.1.0,>=1.0->statsmodels) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas!=2.1.0,>=1.0->statsmodels) (2023.4)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.4->statsmodels) (1.16.0)

In [ ]:
#import libraries
import numpy as np
import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm

In [ ]:
#upload csv file
df=pd.read_csv("/content/electricity.csv")
df.head(18)

,Year,Month,Bill Date,Amount,Unnamed: 4,Calculation Table,Unnamed: 6,Unnamed: 7,Year.1,Paid,Average
0,2020.0,April,16-04-2020,"? 1,283.0",NaN,Total Average,"? 6,139.3",NaN,2020,"? 25,102","? 5,020"
1,2020.0,June,14-06-2020,"? 5,419.0",NaN,Total,"? 1,10,507.0",NaN,April,"? 1,283","? 1,283"
2,2020.0,August,14-08-2020,"? 7,284.0",NaN,Min,? 375.0,NaN,June,"? 5,419","? 5,419"
3,2020.0,October,11-10-2020,"? 10,741.0",NaN,Max,"? 15,359.0",NaN,August,"? 7,284","? 7,284"
4,2020.0,December,05-12-2020,? 375.0,NaN,NaN,NaN,NaN,October,"? 10,741","? 10,741"
5,2021.0,February,14-02-2021,"? 2,074.0",NaN,NaN,NaN,NaN,December,? 375,? 375
6,2021.0,April,10-04-2021,"? 1,225.0",NaN,NaN,NaN,NaN,2021,"? 33,763","? 5,627"
7,2021.0,June,05-06-2021,"? 4,869.0",NaN,NaN,NaN,NaN,February,"? 2,074","? 2,074"
8,2021.0,August,06-08-2021,"? 14,113.0",NaN,NaN,NaN,NaN,April,"? 1,225","? 1,225"
9,2021.0,October,14-10-2021,"? 10,059.0",NaN,NaN,NaN,NaN,June,"? 4,869","? 4,869"
10,2021.0,December,10-10-2021,"? 1,423.0",NaN,NaN,NaN,NaN,August,"? 14,113","? 14,113"
11,2022.0,February,08-02-2022,"? 1,855.0",NaN,NaN,NaN,NaN,October,"? 10,059","? 10,059"
12,2022.0,April,09-02-2022,"? 1,335.0",NaN,NaN,NaN,NaN,December,"? 1,423","? 1,423"
13,2022.0,June,09-06-2022,"? 12,076.0",NaN,NaN,NaN,NaN,2022,"? 48,374","? 8,062"
14,2022.0,August,08-08-2022,"? 15,359.0",NaN,NaN,NaN,NaN,February,"? 1,855","? 1,855"
15,2022.0,October,08-10-2022,"? 14,502.0",NaN,NaN,NaN,NaN,April,"? 1,335","? 1,335"
16,2022.0,December,07-12-2022,"? 3,247.0",NaN,NaN,NaN,NaN,June,"? 12,076","? 12,076"
17,2023.0,February,06-12-2023,"? 3,268.0",NaN,NaN,NaN,NaN,August,"? 15,359","? 15,359"

In [ ]:
#saving the csv file
data=df.to_csv("/content/electricity.csv")

In [ ]:
#creating year and amount columns
column=['Year','Amount']
df_req=df[column]
df_req

      Year        Amount
0   2020.0    ? 1,283.0
1   2020.0    ? 5,419.0
2   2020.0    ? 7,284.0
3   2020.0   ? 10,741.0
4   2020.0      ? 375.0
5   2021.0    ? 2,074.0
6   2021.0    ? 1,225.0
7   2021.0    ? 4,869.0
8   2021.0   ? 14,113.0
9   2021.0   ? 10,059.0
10  2021.0    ? 1,423.0
11  2022.0    ? 1,855.0
12  2022.0    ? 1,335.0
13  2022.0   ? 12,076.0
14  2022.0   ? 15,359.0
15  2022.0   ? 14,502.0
16  2022.0    ? 3,247.0
17  2023.0    ? 3,268.0
18     NaN           NaN
19     NaN           NaN
20     NaN           NaN
21     NaN           NaN
22     NaN           NaN

In [ ]:
#dropping null values
df1=df_req.dropna()

In [ ]:
df1

      Year        Amount
0   2020.0    ? 1,283.0
1   2020.0    ? 5,419.0
2   2020.0    ? 7,284.0
3   2020.0   ? 10,741.0
4   2020.0      ? 375.0
5   2021.0    ? 2,074.0
6   2021.0    ? 1,225.0
7   2021.0    ? 4,869.0
8   2021.0   ? 14,113.0
9   2021.0   ? 10,059.0
10  2021.0    ? 1,423.0
11  2022.0    ? 1,855.0
12  2022.0    ? 1,335.0
13  2022.0   ? 12,076.0
14  2022.0   ? 15,359.0
15  2022.0   ? 14,502.0
16  2022.0    ? 3,247.0
17  2023.0    ? 3,268.0

In [ ]:
#generate sample data
np.random.seed(0)
df1 = pd.DataFrame({
    'Year': np.random.choice(['2020', '2021', '2022'],size=18),
    'Amount':np.random.normal(loc=10, scale=2, size=18)#loc=>mean,scale=>standard deviation
})
print(df1)

    Year     Amount
0   2020   9.058458
1   2021  11.946032
2   2020   7.443702
3   2021  12.874741
4   2021   9.844591
5   2022  12.179260
6   2020  10.193085
7   2022  12.837334
8   2020  12.336546
9   2020  11.894372
10  2020  12.170974
11  2022  14.764449
12  2021   9.187953
13  2022  10.532891
14  2022   7.288573
15  2020   9.771795
16  2021   8.311538
17  2021  11.411282

In [ ]:
#claculate mean amount for each year
mean_score_per_group = df1.groupby('Year')['Amount'].mean()
print(mean_score_per_group)

Year
2020    10.409847
2021    10.596023
2022    11.520501
Name: Amount, dtype: float64

In [ ]:
 #generate random year selections
choices = ['2020', '2021', '2022']
size = 18
year_column = np.random.choice(choices, size=size)
print(year_column)

['2020' '2020' '2020' '2021' '2021' '2022' '2020' '2020' '2021' '2020'
 '2021' '2022' '2022' '2020' '2021' '2021' '2021' '2021']

In [ ]:
#calculate amount values
mean = 10
std = 2
size = 18
Amount_values = mean + std * np.random.randn(size)
print(Amount_values)

[12.46058136 12.4047597   9.22534637  9.3953945   7.90289407  7.15996413
  6.58745962 13.90155079  8.98069564  9.1238514   7.49440928 11.55498071
  6.7722043   9.57451944  8.20906688 10.773805    8.97838972  7.63873563]

In [ ]:
# hypothesis testing (t-test)
group_A = df1[df1['Year'] == '2020']['Amount']
group_B = df1[df1['Year'] == '2021']['Amount']
t_stat, p_value =stats.ttest_ind(group_A, group_B)
print("t-statistic:", t_stat)
print("p-value:", p_value)

t-statistic: -0.18616648409089434
p-value: 0.8557029463822119

In [ ]:
#prediction
if p_value < 0.05:
  print("reject the null hypothesis")
else:
  print("fail to reject the null hypothesis")

fail to reject the null hypothesis

In [ ]:
#ANOVA (one-way ANOVA)
f_stat, p_value = stats.f_oneway(df1[df1['Year']== '2020']['Amount'],
                                 df1[df1['Year']== '2021']['Amount'],
                                 df1[df1['Year']== '2022']['Amount'])
print("F-statistic:",f_stat)
print("p-value:",p_value)

F-statistic: 0.43623602109638376
p-value: 0.6544103539964587